Update CI & requirements

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -18,8 +18,9 @@ jobs:
       matrix:
         python-version: ["3.8", "3.9", "3.10", "3.11"]
 
-    steps:    
-    - uses: actions/checkout@v3
+    steps: 
+    - name: Checkout repository     
+      uses: actions/checkout@v3
     
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v3
@@ -33,12 +34,21 @@ jobs:
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         
     - name: Lint with flake8
+      id: flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Linting failed"
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || echo "Linting failed"
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
         
     - name: Test with pytest
+      id: pytest
       run: |
-        pytest || echo "Tests failed"
+        pytest
+
+    - name: Check linting and tests
+      run: |
+        if [ ${{ steps.flake8.outcome }} == "failure" ] || [ ${{ steps.pytest.outcome }} == "failure" ]; then
+          echo "Linting or tests failed. Preventing further workflow execution."
+          exit 1
+        fi
